"""Adicionando back_populates no relacionamento de Email com Detalhe

Revision ID: 518c8cefdef5
Revises: ad9a0e1bfb54
Create Date: 2025-09-29 12:01:49.601847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518c8cefdef5'
down_revision: Union[str, Sequence[str], None] = 'ad9a0e1bfb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
