"""Adicionar coluna Assunto na Campanha

Revision ID: 69464d9d1340
Revises: 7d761da8fe60
Create Date: 2025-08-27 19:49:42.923041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69464d9d1340'
down_revision: Union[str, Sequence[str], None] = '7d761da8fe60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campanha', sa.Column('Assunto', sa.String(), nullable=True))
    op.add_column('lista', sa.Column('Lixeira', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lista', 'Lixeira')
    op.drop_column('campanha', 'Assunto')
    # ### end Alembic commands ###
