"""Adicionando tabela de UsuarioSmtp

Revision ID: 71ccac60a854
Revises: b803fe4e26a2
Create Date: 2025-09-03 15:00:00.003725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ccac60a854'
down_revision: Union[str, Sequence[str], None] = 'b803fe4e26a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_smtp',
    sa.Column('IdUsuarioSmtp', sa.Integer(), nullable=False),
    sa.Column('Usuario', sa.String(), nullable=False),
    sa.Column('Senha', sa.String(), nullable=False),
    sa.Column('Dominio', sa.String(), nullable=False),
    sa.Column('Porta', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdUsuarioSmtp')
    )
    op.create_index(op.f('ix_usuario_smtp_IdUsuarioSmtp'), 'usuario_smtp', ['IdUsuarioSmtp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_smtp_IdUsuarioSmtp'), table_name='usuario_smtp')
    op.drop_table('usuario_smtp')
    # ### end Alembic commands ###
