"""Adicionar coluna Lixeira na lista

Revision ID: 7d761da8fe60
Revises: 836513e63b5e
Create Date: 2025-08-27 14:47:14.199773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d761da8fe60'
down_revision: Union[str, Sequence[str], None] = '836513e63b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista', sa.Column('Lixeira', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lista', 'Lixeira')
    # ### end Alembic commands ###
