"""Colocando token em envio  para evitar envios duplicados

Revision ID: 9527dc7e96c5
Revises: f6992a5965d1
Create Date: 2025-09-19 23:58:06.072892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9527dc7e96c5'
down_revision: Union[str, Sequence[str], None] = 'f6992a5965d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envio', sa.Column('Token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envio', 'Token')
    # ### end Alembic commands ###
