"""Alterando tabela de Detalhe para começar a ser usada

Revision ID: a2600293d9dc
Revises: d6c315cab522
Create Date: 2025-09-29 11:38:22.596538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2600293d9dc'
down_revision: Union[str, Sequence[str], None] = 'd6c315cab522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalhe', sa.Column('Tipo', sa.Integer(), nullable=False))
    op.add_column('detalhe', sa.Column('Codigo', sa.Integer(), nullable=True))
    op.add_column('detalhe', sa.Column('Email', sa.Integer(), nullable=True))
    op.alter_column('detalhe', 'Envio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_detalhe_Email'), 'detalhe', ['Email'], unique=False)
    op.create_index(op.f('ix_detalhe_Envio'), 'detalhe', ['Envio'], unique=False)
    op.create_foreign_key(None, 'detalhe', 'email', ['Email'], ['IdEmail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalhe', type_='foreignkey')
    op.drop_index(op.f('ix_detalhe_Envio'), table_name='detalhe')
    op.drop_index(op.f('ix_detalhe_Email'), table_name='detalhe')
    op.alter_column('detalhe', 'Envio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('detalhe', 'Email')
    op.drop_column('detalhe', 'Codigo')
    op.drop_column('detalhe', 'Tipo')
    # ### end Alembic commands ###
