"""Alterando Conteudo par nullable=True

Revision ID: ad9a0e1bfb54
Revises: a2600293d9dc
Create Date: 2025-09-29 11:45:56.858474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9a0e1bfb54'
down_revision: Union[str, Sequence[str], None] = 'a2600293d9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalhe', 'Conteudo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalhe', 'Conteudo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
