"""Adicionando EmailFrom em UsuarioSmtp

Revision ID: b3d8bc168a71
Revises: 518c8cefdef5
Create Date: 2025-10-20 16:36:55.207020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d8bc168a71'
down_revision: Union[str, Sequence[str], None] = '518c8cefdef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_smtp', sa.Column('EmailFrom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_smtp', 'EmailFrom')
    # ### end Alembic commands ###
