"""Adicionando tabela de Usuario

Revision ID: b507c3b12844
Revises: 71ccac60a854
Create Date: 2025-09-08 11:07:05.451794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b507c3b12844'
down_revision: Union[str, Sequence[str], None] = '71ccac60a854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdUsuario')
    )
    op.create_index(op.f('ix_usuario_Email'), 'usuario', ['Email'], unique=True)
    op.create_index(op.f('ix_usuario_IdUsuario'), 'usuario', ['IdUsuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_IdUsuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_Email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
