"""Assunot not null

Revision ID: b803fe4e26a2
Revises: 69464d9d1340
Create Date: 2025-08-27 19:53:49.082808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b803fe4e26a2'
down_revision: Union[str, Sequence[str], None] = '69464d9d1340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campanha', 'Assunto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campanha', 'Assunto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
