"""Colocando token em envio  para evitar envios duplicados

Revision ID: d6c315cab522
Revises: 9527dc7e96c5
Create Date: 2025-09-20 00:15:00.411051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c315cab522'
down_revision: Union[str, Sequence[str], None] = '9527dc7e96c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_envio_Token'), 'envio', ['Token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envio_Token'), table_name='envio')
    # ### end Alembic commands ###
