"""Criando campos de IdUsuario em outras tabelas

Revision ID: f6992a5965d1
Revises: 91c6cb254351
Create Date: 2025-09-09 22:41:15.180168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6992a5965d1'
down_revision: Union[str, Sequence[str], None] = '91c6cb254351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campanha', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campanha', 'usuario', ['IdUsuario'], ['IdUsuario'])
    op.add_column('envio', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'envio', 'usuario', ['IdUsuario'], ['IdUsuario'])
    op.add_column('lista', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lista', 'usuario', ['IdUsuario'], ['IdUsuario'])
    op.add_column('usuario_smtp', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario_smtp', 'usuario', ['IdUsuario'], ['IdUsuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_smtp', type_='foreignkey')
    op.drop_column('usuario_smtp', 'IdUsuario')
    op.drop_constraint(None, 'lista', type_='foreignkey')
    op.drop_column('lista', 'IdUsuario')
    op.drop_constraint(None, 'envio', type_='foreignkey')
    op.drop_column('envio', 'IdUsuario')
    op.drop_constraint(None, 'campanha', type_='foreignkey')
    op.drop_column('campanha', 'IdUsuario')
    # ### end Alembic commands ###
