"""Adicionando verificacao de email

Revision ID: faaf505354d3
Revises: b3d8bc168a71
Create Date: 2025-11-18 14:36:54.943314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faaf505354d3'
down_revision: Union[str, Sequence[str], None] = 'b3d8bc168a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('Verificacao', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'Verificacao')
    # ### end Alembic commands ###
